=== javagyanmantraTeam/CCLProject/Rest/SOAPPratic/CreditLimitServiceSOAP-jar/target/classes/CreditLimitReq.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.keybank.org/CreditLimitReq"
	xmlns:req="http://www.keybank.org/CreditLimitReq" 
	elementFormDefault="qualified">
	<element name="CreditLimitReq" type="req:CreditLimitReqType" />
	<complexType name="CreditLimitReqType">
		<sequence>
			<element name="ClientContext" type="req:ClientContextType" />
			<element name="OfferDetail" type="req:OfferDetailType" />
			<element name="ServiceDetail" type="req:ServiceDetailType" />
		</sequence>
	</complexType>
	<complexType name="ClientContextType">
		<sequence>
			<element name="clientId" type="string" />
			<element name="channelId" type="string" />
			<element name="reqId" type="string" />
		</sequence>
	</complexType>
	<complexType name="OfferDetailType">
		<sequence>
			<element name="promocode" type="string"></element>
		</sequence>
	</complexType>
	<complexType name="ServiceDetailType">
		<sequence>
			<element name="serviceName" type="string" />
			<element name="apiName" type="string" />
			<element name="version" type="string" />
		</sequence>
	</complexType>
</schema>

=== javagyanmantraTeam/CCLProject/Rest/SOAPPratic/CreditLimitServiceSOAP-jar/src/main/resources/CreditLimitReq.xml
<?xml version="1.0" encoding="UTF-8"?>
<req:CreditLimitReq xmlns:req="http://www.keybank.org/CreditLimitReq" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.keybank.org/CreditLimitReq CreditLimitReq.xsd ">
  <req:ClientContext>
    <req:clientId>req:clientId</req:clientId>
    <req:channelId>req:channelId</req:channelId>
    <req:reqId>req:reqId</req:reqId>
  </req:ClientContext>
  <req:OfferDetail>
    <req:promocode>req:promocode</req:promocode>
  </req:OfferDetail>
  <req:ServiceDetail>
    <req:serviceName>req:serviceName</req:serviceName>
    <req:apiName>req:apiName</req:apiName>
    <req:version>req:version</req:version>
  </req:ServiceDetail>
</req:CreditLimitReq>
